[build-system]
requires = ["setuptools", "wheel","cython"]
build-backend = "setuptools.build_meta"

[project]
name = "ChessTk"
version = "0.0.1"
description = "Python chess engine with interface written in Tkinter"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "pillow",
    "cairosvg",
    "build"
]

[tool.setuptools]
# Map your package directory if using a src/ layout
package-dir = {"" = "src"}

[[tool.setuptools.ext-modules]]
name = "bitboard"
sources = ["src/bitboard.py"]

[[tool.setuptools.ext-modules]]
name = "gamestate"
sources = ["src/gamestate.py"]
